### ISSUE TITLE
Label for the MiE-X datasets

### ISSUE THREAD

**Issue by noobasuna** [liuyvchi/MiE-X#2]
Hi, I came across to download the datasets but was confused by the folder name. 
Does **000106_oulu_0** means it is positive, **000106_oulu_1** means it is negative and **000106_oulu_2** is surprise?

Thank you!

**Comment by liuyvchi** [comment]
Thanks for your attention. The label mapping should be the same as the MEGC2019 challenge:
negative: 0
positive: 1
surprise: 2

**Comment by noobasuna** [comment]
Noted with thanks!
